set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

init:
    git init
    uv init
    uv add --dev ruff pytest git-cliff

release:
    uv run cz bump
    uv run git-cliff -o CHANGELOG.md
    git add CHANGELOG.md
    git commit -m "chore(changelog): update changelog\"
    git push origin main
    git push origin --tags

format-py:
    uv run ruff check --fix .

mkdir path:
    mkdir -p {{path}}
