set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

init:
    git init
    uv init
    uv add --dev isort autoflake ruff pytest git-cliff

release:
    uv run cz bump
    uv run git-cliff -o CHANGELOG.md
    git add CHANGELOG.md
    git commit -m \"chore(changelog): update changelog\"
    git push origin main
    git push origin --tags

format-py:
    uv run autoflake --in-place --remove-unused-variables --remove-all-unused-imports -r . --exclude '__init__.py'
    uv run isort . --profile black --skip-gitignore
    uv run ruff check --fix . --exit-zero
