name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release

      - run: |
          mkdir dist
          mkdir dist/c2
          copy target\release\c2.exe dist\c2\

      - run: |
          powershell Compress-Archive -Path dist\c2\* -DestinationPath c2-windows-x86_64.zip

      - uses: softprops/action-gh-release@v2
        with:
          files: c2-windows-x86_64.zip