name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release

      - name: Prepare artifact
        run: |
          mkdir dist
          mkdir dist/c2
          copy target\release\c2.exe dist\c2\

      - name: Zip release
        run: |
          powershell Compress-Archive -Path dist\c2\* -DestinationPath c2-windows-x86_64.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: c2-windows-x86_64.zip